// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type RegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type RegisterResponse struct {
	Id int `json:"id"`
}

type UserInfoRequest struct {
	Id int `json:"id"`
}

type UserInfoResponse struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
