// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: apps/ws/proto/chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 极简版消息包装器
type Message struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 核心：只保留聊天和错误反馈（测试时报错也很重要）
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_Chat
	//	*Message_Error
	//	*Message_HeartbeatPing
	//	*Message_HeartbeatPong
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_apps_ws_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_apps_ws_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_apps_ws_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Message) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*Message_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Message) GetHeartbeatPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*Message_HeartbeatPing); ok {
			return x.HeartbeatPing
		}
	}
	return nil
}

func (x *Message) GetHeartbeatPong() *HeartbeatPong {
	if x != nil {
		if x, ok := x.Payload.(*Message_HeartbeatPong); ok {
			return x.HeartbeatPong
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Message_Error struct {
	Error *ErrorMessage `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Message_HeartbeatPing struct {
	HeartbeatPing *HeartbeatPing `protobuf:"bytes,4,opt,name=heartbeat_ping,json=heartbeatPing,proto3,oneof"`
}

type Message_HeartbeatPong struct {
	HeartbeatPong *HeartbeatPong `protobuf:"bytes,5,opt,name=heartbeat_pong,json=heartbeatPong,proto3,oneof"`
}

func (*Message_Chat) isMessage_Payload() {}

func (*Message_Error) isMessage_Payload() {}

func (*Message_HeartbeatPing) isMessage_Payload() {}

func (*Message_HeartbeatPong) isMessage_Payload() {}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`       // 发送者 ID
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`           // 接收者 ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"` // 消息文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_apps_ws_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apps_ws_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_apps_ws_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_apps_ws_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_apps_ws_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_apps_ws_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatPing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientUnixTime int64                  `protobuf:"varint,1,opt,name=client_unix_time,json=clientUnixTime,proto3" json:"client_unix_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_apps_ws_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_apps_ws_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_apps_ws_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatPing) GetClientUnixTime() int64 {
	if x != nil {
		return x.ClientUnixTime
	}
	return 0
}

type HeartbeatPong struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AckRequestId   string                 `protobuf:"bytes,1,opt,name=ack_request_id,json=ackRequestId,proto3" json:"ack_request_id,omitempty"`
	ServerUnixTime int64                  `protobuf:"varint,2,opt,name=server_unix_time,json=serverUnixTime,proto3" json:"server_unix_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_apps_ws_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_apps_ws_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_apps_ws_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatPong) GetAckRequestId() string {
	if x != nil {
		return x.AckRequestId
	}
	return ""
}

func (x *HeartbeatPong) GetServerUnixTime() int64 {
	if x != nil {
		return x.ServerUnixTime
	}
	return 0
}

var File_apps_ws_proto_chat_proto protoreflect.FileDescriptor

const file_apps_ws_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x18apps/ws/proto/chat.proto\x12\x02ws\"\xfc\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x04chat\x18\x02 \x01(\v2\x0f.ws.ChatMessageH\x00R\x04chat\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x10.ws.ErrorMessageH\x00R\x05error\x12:\n" +
	"\x0eheartbeat_ping\x18\x04 \x01(\v2\x11.ws.HeartbeatPingH\x00R\rheartbeatPing\x12:\n" +
	"\x0eheartbeat_pong\x18\x05 \x01(\v2\x11.ws.HeartbeatPongH\x00R\rheartbeatPongB\t\n" +
	"\apayload\"K\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"<\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\rHeartbeatPing\x12(\n" +
	"\x10client_unix_time\x18\x01 \x01(\x03R\x0eclientUnixTime\"_\n" +
	"\rHeartbeatPong\x12$\n" +
	"\x0eack_request_id\x18\x01 \x01(\tR\fackRequestId\x12(\n" +
	"\x10server_unix_time\x18\x02 \x01(\x03R\x0eserverUnixTimeB\x1dZ\x1blark/apps/ws/internal/pb;pbb\x06proto3"

var (
	file_apps_ws_proto_chat_proto_rawDescOnce sync.Once
	file_apps_ws_proto_chat_proto_rawDescData []byte
)

func file_apps_ws_proto_chat_proto_rawDescGZIP() []byte {
	file_apps_ws_proto_chat_proto_rawDescOnce.Do(func() {
		file_apps_ws_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_ws_proto_chat_proto_rawDesc), len(file_apps_ws_proto_chat_proto_rawDesc)))
	})
	return file_apps_ws_proto_chat_proto_rawDescData
}

var file_apps_ws_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apps_ws_proto_chat_proto_goTypes = []any{
	(*Message)(nil),       // 0: ws.Message
	(*ChatMessage)(nil),   // 1: ws.ChatMessage
	(*ErrorMessage)(nil),  // 2: ws.ErrorMessage
	(*HeartbeatPing)(nil), // 3: ws.HeartbeatPing
	(*HeartbeatPong)(nil), // 4: ws.HeartbeatPong
}
var file_apps_ws_proto_chat_proto_depIdxs = []int32{
	1, // 0: ws.Message.chat:type_name -> ws.ChatMessage
	2, // 1: ws.Message.error:type_name -> ws.ErrorMessage
	3, // 2: ws.Message.heartbeat_ping:type_name -> ws.HeartbeatPing
	4, // 3: ws.Message.heartbeat_pong:type_name -> ws.HeartbeatPong
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_apps_ws_proto_chat_proto_init() }
func file_apps_ws_proto_chat_proto_init() {
	if File_apps_ws_proto_chat_proto != nil {
		return
	}
	file_apps_ws_proto_chat_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_Chat)(nil),
		(*Message_Error)(nil),
		(*Message_HeartbeatPing)(nil),
		(*Message_HeartbeatPong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_ws_proto_chat_proto_rawDesc), len(file_apps_ws_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apps_ws_proto_chat_proto_goTypes,
		DependencyIndexes: file_apps_ws_proto_chat_proto_depIdxs,
		MessageInfos:      file_apps_ws_proto_chat_proto_msgTypes,
	}.Build()
	File_apps_ws_proto_chat_proto = out.File
	file_apps_ws_proto_chat_proto_goTypes = nil
	file_apps_ws_proto_chat_proto_depIdxs = nil
}
