services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5 
    container_name: etcd
    restart: unless-stopped
    ports:
      - "2379:2379"
    environment:
      - ETCD_NAME=etcd
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
    healthcheck:
      test: [ "CMD", "/usr/local/bin/etcdctl", "--endpoints=http://127.0.0.1:2379", "endpoint", "health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  apisix:
    image: apache/apisix:latest
    container_name: apisix
    restart: unless-stopped
    depends_on:
      etcd:
        condition: service_healthy
    ports:
      - "9080:9080"
      - "9180:9180"
      - "9443:9443"
    volumes:
      - ../configs/apisix/apisix.conf:/usr/local/apisix/conf/config.yaml:ro

  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    container_name: apisix-dashboard
    restart: unless-stopped
    depends_on:
      etcd:
        condition: service_healthy
    ports:
      - "9000:9000"
    volumes:
      - ../configs/apisix/dashboard.conf:/usr/local/apisix-dashboard/conf/conf.yaml:ro
