// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc.proto

package server

import (
	"context"

	"lark/apps/chat/rpc/internal/logic"
	"lark/apps/chat/rpc/internal/svc"
	"lark/pkg/proto/pb/chat"//todo
)

type SendMessageServer struct {
	svcCtx *svc.ServiceContext
	pb_chat.UnimplementedChatRpcServer
}

func NewSendMessageServer(svcCtx *svc.ServiceContext) *SendMessageServer {
	return &SendMessageServer{
		svcCtx: svcCtx,
	}
}

// func (s *SendMessageServer) Ping(ctx context.Context, in *chat.Request) (*chat.Response, error) {
// 	l := logic.NewPingLogic(ctx, s.svcCtx)
// 	return l.Ping(in)
// }

func (s *SendMessageServer) SendMessage(ctx context.Context, in *pb_chat.SendMessageReq) (*pb_chat.SendMessageResp, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)

}