// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: ws/ws.proto

package pb_ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "lark/pkg/proto/pb/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_COMMAND_UNSPECIFIED    Command = 0
	Command_COMMAND_SEND_MESSAGE   Command = 1 //客户端发信息的命令
	Command_COMMAND_MESSAGE_ACK    Command = 2 //检查信息是否有落库的命令
	Command_COMMAND_MESSAGE_EVENT  Command = 3 //客户端收信息的命令
	Command_COMMAND_SYNC           Command = 4 //客户端断网重连后解决漏信的命令
	Command_COMMAND_SYNC_RESULT    Command = 5
	Command_COMMAND_READ           Command = 6 //客户端已读的命令
	Command_COMMAND_RECALL         Command = 7 //客户端撤回的命令
	Command_COMMAND_HEARTBEAT_PING Command = 8 //心跳检测
	Command_COMMAND_HEARTBEAT_PONG Command = 9
	Command_COMMAND_ERROR          Command = 10 //服务端发送错误的命令
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0:  "COMMAND_UNSPECIFIED",
		1:  "COMMAND_SEND_MESSAGE",
		2:  "COMMAND_MESSAGE_ACK",
		3:  "COMMAND_MESSAGE_EVENT",
		4:  "COMMAND_SYNC",
		5:  "COMMAND_SYNC_RESULT",
		6:  "COMMAND_READ",
		7:  "COMMAND_RECALL",
		8:  "COMMAND_HEARTBEAT_PING",
		9:  "COMMAND_HEARTBEAT_PONG",
		10: "COMMAND_ERROR",
	}
	Command_value = map[string]int32{
		"COMMAND_UNSPECIFIED":    0,
		"COMMAND_SEND_MESSAGE":   1,
		"COMMAND_MESSAGE_ACK":    2,
		"COMMAND_MESSAGE_EVENT":  3,
		"COMMAND_SYNC":           4,
		"COMMAND_SYNC_RESULT":    5,
		"COMMAND_READ":           6,
		"COMMAND_RECALL":         7,
		"COMMAND_HEARTBEAT_PING": 8,
		"COMMAND_HEARTBEAT_PONG": 9,
		"COMMAND_ERROR":          10,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_ws_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_ws_ws_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{0}
}

type MessageEventType int32

const (
	MessageEventType_MESSAGE_EVENT_TYPE_UNSPECIFIED MessageEventType = 0
	MessageEventType_MESSAGE_EVENT_TYPE_NEW         MessageEventType = 1
	MessageEventType_MESSAGE_EVENT_TYPE_DELIVERED   MessageEventType = 2
	MessageEventType_MESSAGE_EVENT_TYPE_READ        MessageEventType = 3
	MessageEventType_MESSAGE_EVENT_TYPE_RECALLED    MessageEventType = 4
	MessageEventType_MESSAGE_EVENT_TYPE_EDITED      MessageEventType = 5
)

// Enum value maps for MessageEventType.
var (
	MessageEventType_name = map[int32]string{
		0: "MESSAGE_EVENT_TYPE_UNSPECIFIED",
		1: "MESSAGE_EVENT_TYPE_NEW",
		2: "MESSAGE_EVENT_TYPE_DELIVERED",
		3: "MESSAGE_EVENT_TYPE_READ",
		4: "MESSAGE_EVENT_TYPE_RECALLED",
		5: "MESSAGE_EVENT_TYPE_EDITED",
	}
	MessageEventType_value = map[string]int32{
		"MESSAGE_EVENT_TYPE_UNSPECIFIED": 0,
		"MESSAGE_EVENT_TYPE_NEW":         1,
		"MESSAGE_EVENT_TYPE_DELIVERED":   2,
		"MESSAGE_EVENT_TYPE_READ":        3,
		"MESSAGE_EVENT_TYPE_RECALLED":    4,
		"MESSAGE_EVENT_TYPE_EDITED":      5,
	}
)

func (x MessageEventType) Enum() *MessageEventType {
	p := new(MessageEventType)
	*p = x
	return p
}

func (x MessageEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ws_ws_proto_enumTypes[1].Descriptor()
}

func (MessageEventType) Type() protoreflect.EnumType {
	return &file_ws_ws_proto_enumTypes[1]
}

func (x MessageEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageEventType.Descriptor instead.
func (MessageEventType) EnumDescriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{1}
}

type Packet struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RequestId  string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Command    Command                `protobuf:"varint,2,opt,name=command,proto3,enum=lark.ws.Command" json:"command,omitempty"`
	DeviceId   string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientTime int64                  `protobuf:"varint,4,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Packet_SendMessage
	//	*Packet_SendAck
	//	*Packet_MessageEvent
	//	*Packet_SyncRequest
	//	*Packet_SyncResponse
	//	*Packet_ReadRequest
	//	*Packet_RecallRequest
	//	*Packet_Ping
	//	*Packet_Pong
	//	*Packet_Error
	Payload       isPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_ws_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Packet) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_COMMAND_UNSPECIFIED
}

func (x *Packet) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Packet) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

func (x *Packet) GetPayload() isPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetSendMessage() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*Packet_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *Packet) GetSendAck() *SendAck {
	if x != nil {
		if x, ok := x.Payload.(*Packet_SendAck); ok {
			return x.SendAck
		}
	}
	return nil
}

func (x *Packet) GetMessageEvent() *MessageEvent {
	if x != nil {
		if x, ok := x.Payload.(*Packet_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

func (x *Packet) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*Packet_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *Packet) GetSyncResponse() *SyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*Packet_SyncResponse); ok {
			return x.SyncResponse
		}
	}
	return nil
}

func (x *Packet) GetReadRequest() *ReadRequest {
	if x != nil {
		if x, ok := x.Payload.(*Packet_ReadRequest); ok {
			return x.ReadRequest
		}
	}
	return nil
}

func (x *Packet) GetRecallRequest() *RecallRequest {
	if x != nil {
		if x, ok := x.Payload.(*Packet_RecallRequest); ok {
			return x.RecallRequest
		}
	}
	return nil
}

func (x *Packet) GetPing() *HeartbeatPing {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Packet) GetPong() *HeartbeatPong {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Packet) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*Packet_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isPacket_Payload interface {
	isPacket_Payload()
}

type Packet_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,10,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type Packet_SendAck struct {
	SendAck *SendAck `protobuf:"bytes,11,opt,name=send_ack,json=sendAck,proto3,oneof"`
}

type Packet_MessageEvent struct {
	MessageEvent *MessageEvent `protobuf:"bytes,12,opt,name=message_event,json=messageEvent,proto3,oneof"`
}

type Packet_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,13,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type Packet_SyncResponse struct {
	SyncResponse *SyncResponse `protobuf:"bytes,14,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

type Packet_ReadRequest struct {
	ReadRequest *ReadRequest `protobuf:"bytes,15,opt,name=read_request,json=readRequest,proto3,oneof"`
}

type Packet_RecallRequest struct {
	RecallRequest *RecallRequest `protobuf:"bytes,16,opt,name=recall_request,json=recallRequest,proto3,oneof"`
}

type Packet_Ping struct {
	Ping *HeartbeatPing `protobuf:"bytes,17,opt,name=ping,proto3,oneof"`
}

type Packet_Pong struct {
	Pong *HeartbeatPong `protobuf:"bytes,18,opt,name=pong,proto3,oneof"`
}

type Packet_Error struct {
	Error *ErrorResponse `protobuf:"bytes,19,opt,name=error,proto3,oneof"`
}

func (*Packet_SendMessage) isPacket_Payload() {}

func (*Packet_SendAck) isPacket_Payload() {}

func (*Packet_MessageEvent) isPacket_Payload() {}

func (*Packet_SyncRequest) isPacket_Payload() {}

func (*Packet_SyncResponse) isPacket_Payload() {}

func (*Packet_ReadRequest) isPacket_Payload() {}

func (*Packet_RecallRequest) isPacket_Payload() {}

func (*Packet_Ping) isPacket_Payload() {}

func (*Packet_Pong) isPacket_Payload() {}

func (*Packet_Error) isPacket_Payload() {}

type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConversionId  string                 `protobuf:"bytes,1,opt,name=conversion_id,json=conversionId,proto3" json:"conversion_id,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MessageType   common.MessageType     `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3,enum=lark.common.MessageType" json:"message_type,omitempty"`
	Body          *common.MessageBody    `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_ws_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessage) GetConversionId() string {
	if x != nil {
		return x.ConversionId
	}
	return ""
}

func (x *SendMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessage) GetMessageType() common.MessageType {
	if x != nil {
		return x.MessageType
	}
	return common.MessageType(0)
}

func (x *SendMessage) GetBody() *common.MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type SendAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Seq            int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	SendTime       int64                  `protobuf:"varint,5,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendAck) Reset() {
	*x = SendAck{}
	mi := &file_ws_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAck) ProtoMessage() {}

func (x *SendAck) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAck.ProtoReflect.Descriptor instead.
func (*SendAck) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{2}
}

func (x *SendAck) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendAck) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendAck) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendAck) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     MessageEventType       `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=lark.ws.MessageEventType" json:"event_type,omitempty"`
	Message       *common.ChatMessage    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Receipt       *common.MessageReceipt `protobuf:"bytes,3,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_ws_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{3}
}

func (x *MessageEvent) GetEventType() MessageEventType {
	if x != nil {
		return x.EventType
	}
	return MessageEventType_MESSAGE_EVENT_TYPE_UNSPECIFIED
}

func (x *MessageEvent) GetMessage() *common.ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetReceipt() *common.MessageReceipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type SyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AfterSeq       int64                  `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_ws_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{4}
}

func (x *SyncRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SyncRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *SyncRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Messages       []*common.ChatMessage  `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	NextSeq        int64                  `protobuf:"varint,3,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	HasMore        bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_ws_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SyncResponse) GetMessages() []*common.ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncResponse) GetNextSeq() int64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReadSeq        int64                  `protobuf:"varint,2,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_ws_ws_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ReadRequest) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type RecallRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_ws_ws_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{7}
}

func (x *RecallRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RecallRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type HeartbeatPing struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientUnixTime int64                  `protobuf:"varint,1,opt,name=client_unix_time,json=clientUnixTime,proto3" json:"client_unix_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_ws_ws_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatPing) GetClientUnixTime() int64 {
	if x != nil {
		return x.ClientUnixTime
	}
	return 0
}

type HeartbeatPong struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AckRequestId   string                 `protobuf:"bytes,1,opt,name=ack_request_id,json=ackRequestId,proto3" json:"ack_request_id,omitempty"`
	ServerUnixTime int64                  `protobuf:"varint,2,opt,name=server_unix_time,json=serverUnixTime,proto3" json:"server_unix_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_ws_ws_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatPong) GetAckRequestId() string {
	if x != nil {
		return x.AckRequestId
	}
	return ""
}

func (x *HeartbeatPong) GetServerUnixTime() int64 {
	if x != nil {
		return x.ServerUnixTime
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_ws_ws_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_ws_ws_proto protoreflect.FileDescriptor

const file_ws_ws_proto_rawDesc = "" +
	"\n" +
	"\vws/ws.proto\x12\alark.ws\x1a\x14common/message.proto\"\xc5\x05\n" +
	"\x06Packet\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\acommand\x18\x02 \x01(\x0e2\x10.lark.ws.CommandR\acommand\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vclient_time\x18\x04 \x01(\x03R\n" +
	"clientTime\x129\n" +
	"\fsend_message\x18\n" +
	" \x01(\v2\x14.lark.ws.SendMessageH\x00R\vsendMessage\x12-\n" +
	"\bsend_ack\x18\v \x01(\v2\x10.lark.ws.SendAckH\x00R\asendAck\x12<\n" +
	"\rmessage_event\x18\f \x01(\v2\x15.lark.ws.MessageEventH\x00R\fmessageEvent\x129\n" +
	"\fsync_request\x18\r \x01(\v2\x14.lark.ws.SyncRequestH\x00R\vsyncRequest\x12<\n" +
	"\rsync_response\x18\x0e \x01(\v2\x15.lark.ws.SyncResponseH\x00R\fsyncResponse\x129\n" +
	"\fread_request\x18\x0f \x01(\v2\x14.lark.ws.ReadRequestH\x00R\vreadRequest\x12?\n" +
	"\x0erecall_request\x18\x10 \x01(\v2\x16.lark.ws.RecallRequestH\x00R\rrecallRequest\x12,\n" +
	"\x04ping\x18\x11 \x01(\v2\x16.lark.ws.HeartbeatPingH\x00R\x04ping\x12,\n" +
	"\x04pong\x18\x12 \x01(\v2\x16.lark.ws.HeartbeatPongH\x00R\x04pong\x12.\n" +
	"\x05error\x18\x13 \x01(\v2\x16.lark.ws.ErrorResponseH\x00R\x05errorB\t\n" +
	"\apayload\"\xc1\x01\n" +
	"\vSendMessage\x12#\n" +
	"\rconversion_id\x18\x01 \x01(\tR\fconversionId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12;\n" +
	"\fmessage_type\x18\x03 \x01(\x0e2\x18.lark.common.MessageTypeR\vmessageType\x12,\n" +
	"\x04body\x18\x04 \x01(\v2\x18.lark.common.MessageBodyR\x04body\"\xa4\x01\n" +
	"\aSendAck\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsend_time\x18\x05 \x01(\x03R\bsendTime\"\xb3\x01\n" +
	"\fMessageEvent\x128\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x19.lark.ws.MessageEventTypeR\teventType\x122\n" +
	"\amessage\x18\x02 \x01(\v2\x18.lark.common.ChatMessageR\amessage\x125\n" +
	"\areceipt\x18\x03 \x01(\v2\x1b.lark.common.MessageReceiptR\areceipt\"i\n" +
	"\vSyncRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa3\x01\n" +
	"\fSyncResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x124\n" +
	"\bmessages\x18\x02 \x03(\v2\x18.lark.common.ChatMessageR\bmessages\x12\x19\n" +
	"\bnext_seq\x18\x03 \x01(\x03R\anextSeq\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"Q\n" +
	"\vReadRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bread_seq\x18\x02 \x01(\x03R\areadSeq\"W\n" +
	"\rRecallRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"9\n" +
	"\rHeartbeatPing\x12(\n" +
	"\x10client_unix_time\x18\x01 \x01(\x03R\x0eclientUnixTime\"_\n" +
	"\rHeartbeatPong\x12$\n" +
	"\x0eack_request_id\x18\x01 \x01(\tR\fackRequestId\x12(\n" +
	"\x10server_unix_time\x18\x02 \x01(\x03R\x0eserverUnixTime\"\\\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId*\x8c\x02\n" +
	"\aCommand\x12\x17\n" +
	"\x13COMMAND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14COMMAND_SEND_MESSAGE\x10\x01\x12\x17\n" +
	"\x13COMMAND_MESSAGE_ACK\x10\x02\x12\x19\n" +
	"\x15COMMAND_MESSAGE_EVENT\x10\x03\x12\x10\n" +
	"\fCOMMAND_SYNC\x10\x04\x12\x17\n" +
	"\x13COMMAND_SYNC_RESULT\x10\x05\x12\x10\n" +
	"\fCOMMAND_READ\x10\x06\x12\x12\n" +
	"\x0eCOMMAND_RECALL\x10\a\x12\x1a\n" +
	"\x16COMMAND_HEARTBEAT_PING\x10\b\x12\x1a\n" +
	"\x16COMMAND_HEARTBEAT_PONG\x10\t\x12\x11\n" +
	"\rCOMMAND_ERROR\x10\n" +
	"*\xd1\x01\n" +
	"\x10MessageEventType\x12\"\n" +
	"\x1eMESSAGE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_EVENT_TYPE_NEW\x10\x01\x12 \n" +
	"\x1cMESSAGE_EVENT_TYPE_DELIVERED\x10\x02\x12\x1b\n" +
	"\x17MESSAGE_EVENT_TYPE_READ\x10\x03\x12\x1f\n" +
	"\x1bMESSAGE_EVENT_TYPE_RECALLED\x10\x04\x12\x1d\n" +
	"\x19MESSAGE_EVENT_TYPE_EDITED\x10\x05B\x1cZ\x1alark/pkg/proto/pb/ws;pb_wsb\x06proto3"

var (
	file_ws_ws_proto_rawDescOnce sync.Once
	file_ws_ws_proto_rawDescData []byte
)

func file_ws_ws_proto_rawDescGZIP() []byte {
	file_ws_ws_proto_rawDescOnce.Do(func() {
		file_ws_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_ws_proto_rawDesc), len(file_ws_ws_proto_rawDesc)))
	})
	return file_ws_ws_proto_rawDescData
}

var file_ws_ws_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ws_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ws_ws_proto_goTypes = []any{
	(Command)(0),                  // 0: lark.ws.Command
	(MessageEventType)(0),         // 1: lark.ws.MessageEventType
	(*Packet)(nil),                // 2: lark.ws.Packet
	(*SendMessage)(nil),           // 3: lark.ws.SendMessage
	(*SendAck)(nil),               // 4: lark.ws.SendAck
	(*MessageEvent)(nil),          // 5: lark.ws.MessageEvent
	(*SyncRequest)(nil),           // 6: lark.ws.SyncRequest
	(*SyncResponse)(nil),          // 7: lark.ws.SyncResponse
	(*ReadRequest)(nil),           // 8: lark.ws.ReadRequest
	(*RecallRequest)(nil),         // 9: lark.ws.RecallRequest
	(*HeartbeatPing)(nil),         // 10: lark.ws.HeartbeatPing
	(*HeartbeatPong)(nil),         // 11: lark.ws.HeartbeatPong
	(*ErrorResponse)(nil),         // 12: lark.ws.ErrorResponse
	(common.MessageType)(0),       // 13: lark.common.MessageType
	(*common.MessageBody)(nil),    // 14: lark.common.MessageBody
	(*common.ChatMessage)(nil),    // 15: lark.common.ChatMessage
	(*common.MessageReceipt)(nil), // 16: lark.common.MessageReceipt
}
var file_ws_ws_proto_depIdxs = []int32{
	0,  // 0: lark.ws.Packet.command:type_name -> lark.ws.Command
	3,  // 1: lark.ws.Packet.send_message:type_name -> lark.ws.SendMessage
	4,  // 2: lark.ws.Packet.send_ack:type_name -> lark.ws.SendAck
	5,  // 3: lark.ws.Packet.message_event:type_name -> lark.ws.MessageEvent
	6,  // 4: lark.ws.Packet.sync_request:type_name -> lark.ws.SyncRequest
	7,  // 5: lark.ws.Packet.sync_response:type_name -> lark.ws.SyncResponse
	8,  // 6: lark.ws.Packet.read_request:type_name -> lark.ws.ReadRequest
	9,  // 7: lark.ws.Packet.recall_request:type_name -> lark.ws.RecallRequest
	10, // 8: lark.ws.Packet.ping:type_name -> lark.ws.HeartbeatPing
	11, // 9: lark.ws.Packet.pong:type_name -> lark.ws.HeartbeatPong
	12, // 10: lark.ws.Packet.error:type_name -> lark.ws.ErrorResponse
	13, // 11: lark.ws.SendMessage.message_type:type_name -> lark.common.MessageType
	14, // 12: lark.ws.SendMessage.body:type_name -> lark.common.MessageBody
	1,  // 13: lark.ws.MessageEvent.event_type:type_name -> lark.ws.MessageEventType
	15, // 14: lark.ws.MessageEvent.message:type_name -> lark.common.ChatMessage
	16, // 15: lark.ws.MessageEvent.receipt:type_name -> lark.common.MessageReceipt
	15, // 16: lark.ws.SyncResponse.messages:type_name -> lark.common.ChatMessage
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_ws_ws_proto_init() }
func file_ws_ws_proto_init() {
	if File_ws_ws_proto != nil {
		return
	}
	file_ws_ws_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_SendMessage)(nil),
		(*Packet_SendAck)(nil),
		(*Packet_MessageEvent)(nil),
		(*Packet_SyncRequest)(nil),
		(*Packet_SyncResponse)(nil),
		(*Packet_ReadRequest)(nil),
		(*Packet_RecallRequest)(nil),
		(*Packet_Ping)(nil),
		(*Packet_Pong)(nil),
		(*Packet_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_ws_proto_rawDesc), len(file_ws_ws_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_ws_proto_goTypes,
		DependencyIndexes: file_ws_ws_proto_depIdxs,
		EnumInfos:         file_ws_ws_proto_enumTypes,
		MessageInfos:      file_ws_ws_proto_msgTypes,
	}.Build()
	File_ws_ws_proto = out.File
	file_ws_ws_proto_goTypes = nil
	file_ws_ws_proto_depIdxs = nil
}
