// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rpc.proto

package chatrpc

import (
	"context"

	"lark/pkg/proto/pb/chat"//todo

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = pb_chat.SendMessageReq
	Response = pb_chat.SendMessageResp

	ChatRpc interface {
		SendMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultChatRpc struct {
		cli zrpc.Client
	}
)

func NewChatRpc(cli zrpc.Client) ChatRpc {
	return &defaultChatRpc{
		cli: cli,
	}
}

func (m *defaultChatRpc) SendMessage(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pb_chat.NewChatRpcClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}
