// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: common/message.proto

package pb_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 会话类型
type ConversationType int32

const (
	ConversationType_CONVERSATION_TYPE_UNSPECIFIED ConversationType = 0
	ConversationType_CONVERSATION_TYPE_SINGLE      ConversationType = 1 //单聊
)

// Enum value maps for ConversationType.
var (
	ConversationType_name = map[int32]string{
		0: "CONVERSATION_TYPE_UNSPECIFIED",
		1: "CONVERSATION_TYPE_SINGLE",
	}
	ConversationType_value = map[string]int32{
		"CONVERSATION_TYPE_UNSPECIFIED": 0,
		"CONVERSATION_TYPE_SINGLE":      1,
	}
)

func (x ConversationType) Enum() *ConversationType {
	p := new(ConversationType)
	*p = x
	return p
}

func (x ConversationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_message_proto_enumTypes[0].Descriptor()
}

func (ConversationType) Type() protoreflect.EnumType {
	return &file_common_message_proto_enumTypes[0]
}

func (x ConversationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationType.Descriptor instead.
func (ConversationType) EnumDescriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_IMAGE       MessageType = 2
	MessageType_MESSAGE_TYPE_FILE        MessageType = 3
	MessageType_MESSAGE_TYPE_SYSTEM      MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_IMAGE",
		3: "MESSAGE_TYPE_FILE",
		4: "MESSAGE_TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_IMAGE":       2,
		"MESSAGE_TYPE_FILE":        3,
		"MESSAGE_TYPE_SYSTEM":      4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_message_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_common_message_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{1}
}

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_DELIVERED   MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_READ        MessageStatus = 3
	MessageStatus_MESSAGE_STATUS_RECALLED    MessageStatus = 4
	MessageStatus_MESSAGE_STATUS_DELETED     MessageStatus = 5
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_SENT",
		2: "MESSAGE_STATUS_DELIVERED",
		3: "MESSAGE_STATUS_READ",
		4: "MESSAGE_STATUS_RECALLED",
		5: "MESSAGE_STATUS_DELETED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_SENT":        1,
		"MESSAGE_STATUS_DELIVERED":   2,
		"MESSAGE_STATUS_READ":        3,
		"MESSAGE_STATUS_RECALLED":    4,
		"MESSAGE_STATUS_DELETED":     5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_message_proto_enumTypes[2].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_common_message_proto_enumTypes[2]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{2}
}

type Conversation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationId   string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationType ConversationType       `protobuf:"varint,2,opt,name=conversation_type,json=conversationType,proto3,enum=lark.common.ConversationType" json:"conversation_type,omitempty"`
	MemberIds        []string               `protobuf:"bytes,3,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"` // 单聊时固定两个
	MaxSeq           int64                  `protobuf:"varint,4,opt,name=max_seq,json=maxSeq,proto3" json:"max_seq,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_common_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Conversation) GetConversationType() ConversationType {
	if x != nil {
		return x.ConversationType
	}
	return ConversationType_CONVERSATION_TYPE_UNSPECIFIED
}

func (x *Conversation) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *Conversation) GetMaxSeq() int64 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *Conversation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Conversation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_common_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{1}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ImageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_common_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{2}
}

func (x *ImageContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageContent) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageContent) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageContent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_common_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{3}
}

func (x *FileContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileContent) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileContent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type MessageBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*MessageBody_Text
	//	*MessageBody_Image
	//	*MessageBody_File
	Content       isMessageBody_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBody) Reset() {
	*x = MessageBody{}
	mi := &file_common_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBody) ProtoMessage() {}

func (x *MessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBody.ProtoReflect.Descriptor instead.
func (*MessageBody) Descriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{4}
}

func (x *MessageBody) GetContent() isMessageBody_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessageBody) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*MessageBody_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *MessageBody) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.Content.(*MessageBody_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *MessageBody) GetFile() *FileContent {
	if x != nil {
		if x, ok := x.Content.(*MessageBody_File); ok {
			return x.File
		}
	}
	return nil
}

type isMessageBody_Content interface {
	isMessageBody_Content()
}

type MessageBody_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type MessageBody_Image struct {
	Image *ImageContent `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type MessageBody_File struct {
	File *FileContent `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

func (*MessageBody_Text) isMessageBody_Content() {}

func (*MessageBody_Image) isMessageBody_Content() {}

func (*MessageBody_File) isMessageBody_Content() {}

type ChatMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`         //服务端生成，落库主键
	ClientMsgId    string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"` //客户端生成，防重试
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MessageType    MessageType            `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3,enum=lark.common.MessageType" json:"message_type,omitempty"`
	Body           *MessageBody           `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Seq            int64                  `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"` //会话内严格递增
	Status         MessageStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=lark.common.MessageStatus" json:"status,omitempty"`
	SendTime       int64                  `protobuf:"varint,9,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	EditTime       int64                  `protobuf:"varint,10,opt,name=edit_time,json=editTime,proto3" json:"edit_time,omitempty"`
	RecallTime     int64                  `protobuf:"varint,11,opt,name=recall_time,json=recallTime,proto3" json:"recall_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_common_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *ChatMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ChatMessage) GetBody() *MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ChatMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ChatMessage) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *ChatMessage) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *ChatMessage) GetEditTime() int64 {
	if x != nil {
		return x.EditTime
	}
	return 0
}

func (x *ChatMessage) GetRecallTime() int64 {
	if x != nil {
		return x.RecallTime
	}
	return 0
}

type MessageReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeliveredSeq   int64                  `protobuf:"varint,4,opt,name=delivered_seq,json=deliveredSeq,proto3" json:"delivered_seq,omitempty"`
	ReadSeq        int64                  `protobuf:"varint,5,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	OperateTime    int64                  `protobuf:"varint,6,opt,name=operate_time,json=operateTime,proto3" json:"operate_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReceipt) Reset() {
	*x = MessageReceipt{}
	mi := &file_common_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReceipt) ProtoMessage() {}

func (x *MessageReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_common_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReceipt.ProtoReflect.Descriptor instead.
func (*MessageReceipt) Descriptor() ([]byte, []int) {
	return file_common_message_proto_rawDescGZIP(), []int{6}
}

func (x *MessageReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageReceipt) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageReceipt) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MessageReceipt) GetDeliveredSeq() int64 {
	if x != nil {
		return x.DeliveredSeq
	}
	return 0
}

func (x *MessageReceipt) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *MessageReceipt) GetOperateTime() int64 {
	if x != nil {
		return x.OperateTime
	}
	return 0
}

var File_common_message_proto protoreflect.FileDescriptor

const file_common_message_proto_rawDesc = "" +
	"\n" +
	"\x14common/message.proto\x12\vlark.common\"\xf9\x01\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12J\n" +
	"\x11conversation_type\x18\x02 \x01(\x0e2\x1d.lark.common.ConversationTypeR\x10conversationType\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\tR\tmemberIds\x12\x17\n" +
	"\amax_seq\x18\x04 \x01(\x03R\x06maxSeq\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"b\n" +
	"\fImageContent\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\"m\n" +
	"\vFileContent\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\"\xab\x01\n" +
	"\vMessageBody\x12.\n" +
	"\x04text\x18\x01 \x01(\v2\x18.lark.common.TextContentH\x00R\x04text\x121\n" +
	"\x05image\x18\x02 \x01(\v2\x19.lark.common.ImageContentH\x00R\x05image\x12.\n" +
	"\x04file\x18\x03 \x01(\v2\x18.lark.common.FileContentH\x00R\x04fileB\t\n" +
	"\acontent\"\xa2\x03\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12;\n" +
	"\fmessage_type\x18\x05 \x01(\x0e2\x18.lark.common.MessageTypeR\vmessageType\x12,\n" +
	"\x04body\x18\x06 \x01(\v2\x18.lark.common.MessageBodyR\x04body\x12\x10\n" +
	"\x03seq\x18\a \x01(\x03R\x03seq\x122\n" +
	"\x06status\x18\b \x01(\x0e2\x1a.lark.common.MessageStatusR\x06status\x12\x1b\n" +
	"\tsend_time\x18\t \x01(\x03R\bsendTime\x12\x1b\n" +
	"\tedit_time\x18\n" +
	" \x01(\x03R\beditTime\x12\x1f\n" +
	"\vrecall_time\x18\v \x01(\x03R\n" +
	"recallTime\"\xd4\x01\n" +
	"\x0eMessageReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rdelivered_seq\x18\x04 \x01(\x03R\fdeliveredSeq\x12\x19\n" +
	"\bread_seq\x18\x05 \x01(\x03R\areadSeq\x12!\n" +
	"\foperate_time\x18\x06 \x01(\x03R\voperateTime*S\n" +
	"\x10ConversationType\x12!\n" +
	"\x1dCONVERSATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONVERSATION_TYPE_SINGLE\x10\x01*\x8a\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x02\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x03\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x04*\xb8\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x02\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x03\x12\x1b\n" +
	"\x17MESSAGE_STATUS_RECALLED\x10\x04\x12\x1a\n" +
	"\x16MESSAGE_STATUS_DELETED\x10\x05B$Z\"lark/pkg/proto/pb/common;pb_commonb\x06proto3"

var (
	file_common_message_proto_rawDescOnce sync.Once
	file_common_message_proto_rawDescData []byte
)

func file_common_message_proto_rawDescGZIP() []byte {
	file_common_message_proto_rawDescOnce.Do(func() {
		file_common_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_message_proto_rawDesc), len(file_common_message_proto_rawDesc)))
	})
	return file_common_message_proto_rawDescData
}

var file_common_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_message_proto_goTypes = []any{
	(ConversationType)(0),  // 0: lark.common.ConversationType
	(MessageType)(0),       // 1: lark.common.MessageType
	(MessageStatus)(0),     // 2: lark.common.MessageStatus
	(*Conversation)(nil),   // 3: lark.common.Conversation
	(*TextContent)(nil),    // 4: lark.common.TextContent
	(*ImageContent)(nil),   // 5: lark.common.ImageContent
	(*FileContent)(nil),    // 6: lark.common.FileContent
	(*MessageBody)(nil),    // 7: lark.common.MessageBody
	(*ChatMessage)(nil),    // 8: lark.common.ChatMessage
	(*MessageReceipt)(nil), // 9: lark.common.MessageReceipt
}
var file_common_message_proto_depIdxs = []int32{
	0, // 0: lark.common.Conversation.conversation_type:type_name -> lark.common.ConversationType
	4, // 1: lark.common.MessageBody.text:type_name -> lark.common.TextContent
	5, // 2: lark.common.MessageBody.image:type_name -> lark.common.ImageContent
	6, // 3: lark.common.MessageBody.file:type_name -> lark.common.FileContent
	1, // 4: lark.common.ChatMessage.message_type:type_name -> lark.common.MessageType
	7, // 5: lark.common.ChatMessage.body:type_name -> lark.common.MessageBody
	2, // 6: lark.common.ChatMessage.status:type_name -> lark.common.MessageStatus
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_common_message_proto_init() }
func file_common_message_proto_init() {
	if File_common_message_proto != nil {
		return
	}
	file_common_message_proto_msgTypes[4].OneofWrappers = []any{
		(*MessageBody_Text)(nil),
		(*MessageBody_Image)(nil),
		(*MessageBody_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_message_proto_rawDesc), len(file_common_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_message_proto_goTypes,
		DependencyIndexes: file_common_message_proto_depIdxs,
		EnumInfos:         file_common_message_proto_enumTypes,
		MessageInfos:      file_common_message_proto_msgTypes,
	}.Build()
	File_common_message_proto = out.File
	file_common_message_proto_goTypes = nil
	file_common_message_proto_depIdxs = nil
}
